language: php
 
php:
  - 5.6
  - 7.0
  - 7.2
  - 7.3

install:
  - printf "\n" | pecl install imagick
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit
